# uncomment to preview locally
#theme: "just-the-docs"
remote_theme: dendronhq/dendron-jekyll
title: CoopCycle
email: contact@coopcycle.org
twitter_username: coopcycle
github_username:  coopcycle
logo: "/assets/images/logo.png"
exclude: [ "node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile", "*/dendron.template.release.md"
]
footer_content: ""

gh_edit_link: true 
gh_edit_repository: "https://github.com/agichim/coopcycle-docs"
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_branch: "master" # the branch that your docs is served from
gh_root: "docs/" # doc root
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately
dendron_vault_path: "vault"



# seo
tagline: "Official documentation for CoopCycle"
description: "This is the official documentation for the CoopCycle software and apps."
twitter:
  card: summary
  username: coopcycle
author:
  twitter: coopcycle

defaults:
  -
    scope:
      path: "notes" # an empty string here means all files in the project
    values:
      layout: "default"
      image: "/assets/images/logo.png"
